server:
  port: 8081
spring:
  application:
    name: yjshz-core
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis_project?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 15915255868
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5s
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  # AI服务配置
ai:
  consultant:
    url: http://localhost:8084


mybatis-plus:
  type-aliases-package: com.yjshz.entity # 别名扫描包
logging:
  level:
    com.yjshz: debug